# Fichero de configuraci贸n para los contenedores del cliente de la aplicaci贸n CarShare
version: "3.8"
services:
  # Crea un contenedor con la api de la aplicaci贸n
  vue:
    # La imagen del contenedor se construye sobre una adecuando las necesidades
    env_file:
      - .env
    build: 
      dockerfile: ./dockerfile
      args:
        - APP_NAME=${APP_NAME}
    # Nombre asignado al contenedor
    container_name: init 
    # Para la versi贸n de desarrollo se mapea la carpeta con una local
    ports: 
      - ${APP_PORT}:8080
    volumes:
      - .:/usr/src/apps
    networks:
      - vue
networks:
    vue:
      driver: bridge
